name: Release

on:
  release:
    types: [created]

jobs:
  update-version-build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    
    - name: Update version in build.gradle.kts
      run: |
        VERSION=$(echo ${{ github.ref }} | sed 's/^refs\/tags\/v//')
        sed -i "s/version = \".*\"/version = \"$VERSION\"/" build.gradle.kts
    
    - name: Build with Gradle
      run: ./gradlew build

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git checkout -b temp-branch
        git add build.gradle.kts
        git commit -m "Update version to ${{ github.ref_name }}"
        git push origin temp-branch:master
